version: 2.19

workflows:
  version: 2
  test:
    jobs:
      - test-3-6
      - test-3-7
      - test-3-8
      - check-black
#      - flake8
#      - mypy
      - publish:
          requires:
#            - flake8
#            - mypy
            - check-black
            - test-3-6
            - test-3-7
            - test-3-8
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - upload-codecov:
          requires:
            - publish
          filters:
            branches:
              only: master
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/

defaults: &defaults
  docker:
    - image: circleci/python:3.8.2

cache-key: &cache-key
  deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}

restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: *cache-key

save_cache: &save_cache
  save_cache:
    key: *cache-key
    paths:
     - .venv

install_envo: &install_envo
  run:
    name: Install envo
    command: python -m venv .venv && ./.venv/bin/pip install envo==0.9.4.15b

bootstrap: &bootstrap
  run:
    name: Bootstrap
    command: bootstrap
    shell: ./.venv/bin/envo ci


jobs:
  flake8:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Flake8
          command: flake
          shell: ./.venv/bin/envo ci
      - *save_cache

  mypy:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Mypy
          command: mypy
          shell: ./.venv/bin/envo ci
      - *save_cache

  check-black:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Black
          command: check_black
          shell: ./.venv/bin/envo ci
      - *save_cache

  test-3-6:
    <<: *defaults
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: test
          shell: ./.venv/bin/envo ci
      - *save_cache

  test-3-7:
    <<: *defaults
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: test
          shell: ./.venv/bin/envo ci
      - *save_cache

  test-3-8:
    <<: *defaults
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Test
          command: test
          shell: ./.venv/bin/envo ci
      - store_artifacts:
          path: workspace
          destination: artifacts
      - store_test_results:
          path: workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - cov.xml
      - *save_cache

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - run:
          name: Generate version
          command: generate_version
          shell: ./.venv/bin/envo ci
      - run:
          name: Build
          command: build
          shell: ./.venv/bin/envo ci
      - run:
          name: publish
          command: publish
          shell: ./.venv/bin/envo ci
      - *save_cache

  upload-codecov:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_envo
      - *bootstrap
      - attach_workspace:
          at: workspace
      - run:
          name: Upload code-cov
          command: upload_codecov
          shell: ./.venv/bin/envo ci
      - *save_cache