defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.7
      environment:
        PIPENV_VENV_IN_PROJECT: true

install_packages: &install_packages
  run:
    name: Install developer packages
    command: |
      sudo pip install pipenv
      pipenv install -d
      pipenv run python setup.py clean

restore_cache: &restore_cache
  restore_cache:
    name: "Restore cache"
    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

version: 2
jobs:
  test-lib:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - *restore_cache
      - run:
          name: Start docker compose
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: Run tests
          command: |
            mkdir test-results
            docker exec stickybeak pipenv run pytest
      - run:
          name: Run tests
          command: |
            pipenv run mypy . | tee ./test-results/mypy.txt
      - run:
          name: Run rstcheck
          command: |
            pipenv run rstcheck README.rst| tee ./test-results/rstcheck.txt

      - store_artifacts:
          path: test-results
          destination: artifacts
      - store_test_results:
          path: test-results

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_packages
      - run:
          name: Build a package
          command: |
            bash ./bin/build
      - run:
          name: Publish the package
          command: |
            bash ./bin/publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-lib:
          filters:
            tags:
                only: /.*/
#      - publish:
#          requires:
#            - test-lib
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^[0-9]+(\.[0-9]+)*$/
#
